benmcollins/libjwt

libjwt/jwt.c
tests/jwt_new.c

As we discussed, when decoding a token, header verification should fail if alg is None and a key is provided by the caller. I added it in the code as well as a test case.
Regards,
Anthony Deroche

Add rejection of token if alg is none and a key is provided

---

include/jwt.h
libjwt/jwt.c
tests/jwt_dump.c
tests/jwt_encode.c
tests/jwt_grant.c
tests/jwt_new.c

According to the JWT spec, exp and iat should be stored as integers, not strings.
Other libraries create exp and iat as integers.  To read and validate that
the JWT is not expired, we have to read the exp value.  Currently, this
library assumes all variables in the JWT are strings, and returns NULL when trying to get the grant for exp. This pull provides a getter for integer grants.
There's another more complex pull request out there, but this one is small and addresses just the core concern of validating that a JWT is not expired.

Added a function to get integer types (like exp and iat)

---

libjwt/jwt.c

I'm not a guru in BIO coding, but without this fix I see memory leak in my example

Fix BIO leak

---

libjwt/jwt.c

Buffer returned by jwt_b64_decode (jwt.c:525) must be freed
Signed-off-by: Tatiana Jamison <tjamison@jaguarlandrover.com>

Fix memory leak in jwt_verify_sha_pem

---

libjwt/jwt.c

`jwt->alg` value was not duplicated, which caused problems

Jwt dup bugfix

---

include/jwt.h
libjwt/jwt.c

Since functions `jwt_dump_fp` and `jwt_encode_fp` use a `FILE` parameter in their description, we need to include `stdio.h` in the project.
But this fie is included in `jwt.c`, which means that if I include `jwt.h` in other projects, I will need to include `stdio.h` too, even if I don't need it, otherwise I will have a compilation error.

Avoid error messages when stdio.h is not included

---

libjwt/jwt.c

This resolves issue #35 by stop accessing OpenSSL data structures members directly. Instead, use accessor/settor functions.
For OpenSSL versions below 1.1.0, we simply define those functions in `jwt.c`.
For more details behind this pull request, see [1.1 API Changes - OpenSSLWiki](https://wiki.openssl.org/index.php/1.1_API_Changes).

Make libjwt compatible with OpenSSL 1.1.0

---

CMakeLists.txt

With this change we can build in Debian stretch.
Signed-off-by: Nelson Castillo <nelsoneci@gmail.com>

Downgrade required CMake Version (3.9 => 3.7)

---

CMakeLists.txt

This was necessary in order to compile the library on OS X 10.13.6. The compiler error (using a CMake build) would issue `alias are not supported on darwin`. We needed to set the `NO_WEAK_ALIASES` flag for Apple

CMake change for OS X 10.13.6 compilation

---

libjwt/Makefile.am
tests/jwt_dump.c
tests/jwt_encode.c

This fixes `.dll` support on MinGW-w64 by adding the `-no-undefined` flag to `LDFLAGS`, and fixes 2 test cases on Windows involving the null device, which is named `nul` rather than `/dev/null`.

Fix dll support on MinGW-w64 and fix test cases on Win32

---

include/jwt.h
libjwt/jwt.c
tests/jwt_dump.c

Intro
This extends JWT/JWS for applications which use custom 'typ' header, such as PASSporT JWT/JWS for STIR-Shaken.
Description
The 'typ' header describes the type of JWT. This is recommended to be "JWT" but can be different for applications which must signal presence of application specific information in JWT (see 1, 2). In particular PASSporT JWS requires typ param to be of value "passport" (see 3), but libjwt before this change would replace such header with typ="JWT" when printed with jwt_dump_str().
Solution
This change allows for any value of 'typ' header in jwt_write_head(). That function will now only attempt to add a header of type 'JWT' and will not unconditionally replace it, so it is added (with default value of 'JWT') only if it is not defined yet.
Compatibility
This …

Allow for custom value of 'typ' header

---

libjwt/jwt.c
tests/jwt_new.c

This relaxes condition requiring 'typ' header
to always be 'JWT', allowing applications extending
JWT to signal that through 'typ' header.

Allow for any value of 'typ' header when decoding

---

libjwt/jwt.c

According to [https://tools.ietf.org/html/rfc7515#section-4.1.1](https://tools.ietf.org/html/rfc7515#section-4.1.1) the "alg" claim is case sensitive and should be treated as such.

Follow spec of "alg" claim being case-sensitive

---

.gitignore
CMakeLists.txt

Hello,
When building on Windows I get compilation errors.
`invalid numeric argument '/Werror'`
This PR works around the issue (for me) by making a compiler flag to only optionally build the examples.  By default it will build the examples so as to not break previous behaviour.

Make building examples optional

---

.gitignore
dist/Makefile.am
dist/libjwt.spec.in

Consistently use /rpmbuild if make is run from /dist
Also ignore the /rpmbuild directory

Fix RPM build

---

examples/main-auth.c
examples/main-gen.c

Fix OSX building error
```
libjwt/examples/main-gen.c:86:10: error: implicit declaration of function 'basename' is invalid in
C99 [-Werror,-Wimplicit-function-declaration]
usage(basename(argv[0]));
```

Fix OSX build error

---

include/jwt.h
libjwt/jwt-gnutls.c
libjwt/jwt-openssl.c
libjwt/jwt-private.h
libjwt/jwt.c
tests/jwt_new.c

The current JWT decoding scheme where the key has to be known upfront is in many cases less than ideal.
For example, if the token is obtained from an external provider, the public key typically changes over time. The JWT standard solves these chicken-and-egg problems by allowing various parameters that can hint at the appropriate key, such as "kid" (Key Id), "x5u" (URL where the current key resides). In fact, any parameter can be used for this purpose (eg, combination of "iss", "kid" and "x5u"). Furthermore, the key can be embedded in the token. All these schemes are hard (impossible?) to implement using the current API which insists on knowing the key before decoding. In this PR, I've proposed a new API (jwt_decode_2) that parses the token first (without any cryptographic verification) …

Separate JWT parsing from verification + decoding with a key obtained from the properties of incoming JWT tokens

---

libjwt/jwt.c

Simple patch to avoid a memory leak if jwt is NULL in jwt_decode()

Avoid memory leak if jwt is NULL

---

examples/main-gen.c
libjwt/CMakeLists.txt

- Allows users who are building jansson from source to use this JWT library.
- I wasn't sure why `jansson` was aliased as `jansson::jansson`. I don't typically pull in dependencies via `find_package` so I don't want to break anything with this change: https://github.com/benmcollins/libjwt/compare/master...lugehorsam:luke/cmake-fetchcontent-support?expand=1#diff-40f7f6521df07450ee749285035f76d6d884a728852df0a212a4bda03d260a9aR93
Could someone who is currently using `find_package` let me know why this `jansson::jansson` alias is done and if I am breaking backwards compatibility by changing it?

only run find_package on jansson if it is not installed

---

libjwt/CMakeLists.txt

Unknown CMake command "PKG_SEARCH_MODULE".

Fix error when using provided jansson

---

libjwt/jwt-openssl.c
libjwt/jwt.c

```
jwt-openssl.c:192:27: error: ‘RSA_PKCS1_PSS_PADDING’ undeclared (first use in this function)
192 |                 padding = RSA_PKCS1_PSS_PADDING;
|                           ^~~~~~~~~~~~~~~~~~~~~
jwt.c:1620: error: 'for' loop initial declaration used outside C99 mode
```

Fix compilation

---

include/jwt.h
libjwt/jwt.c
tests/jwt_dump.c

This PR adds a separate method for dumping only body (grants) of the JWT. It's needed in some cases where enumerating all grants is overkill and getting the whole grants string is the only option.

Implement dump grants as string

---

libjwt/jwt-openssl.c

```
jwt-openssl.c:281:17: warning: 'EVP_PKEY_get1_EC_KEY' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
281 |                 ec_key = EVP_PKEY_get1_EC_KEY(pkey);
|                 ^~~~~~
jwt-openssl.c:285:17: warning: 'EC_KEY_get0_group' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
285 |                 degree = EC_GROUP_get_degree(EC_KEY_get0_group(ec_key));
|                 ^~~~~~
```

Fix OpenSSL 3 deprecation warnings

---

libjwt/jwks-curl.c

Header field names are case-insensitive. This is explicitly stated in RFC 2616, Section 4.2

Fix case-sensitive check for Content-Length
